### ISSUE TITLE
MacOS editor and terminal readonly after changed file has been reloaded in 4.15.0

### ISSUE THREAD

**Issue by raymanP** [pyzo/pyzo#1046]
When code has been executed and a file has been reloaded after external change, there is no possibility anymore to edit code or type anything into the console.

I don't know if its due to the macOS update (using lastest macos 14.5) or a new error in pyzo 4.15.0

Only after reopeining of Pyzo it is working again.

Thanks for the great program, raymanP

**Comment by bdieterm** [comment]
That's hard to diagnose because I have no mac computer where I could try to reproduce that problem. On Linux and MS Windows I have never encountered such a problem.

This could be some issue with the Qt framework or PySide6.

Does this problem also occur with older versions of Pyzo, and if yes what is the newest version that hasn't such a problem?

Try to start Pyzo normally, then open the "Logger" tool so that you see the logger shell ("Tools -> Logger" in Pyzo's menu). Then reproduce the problem by changing the loaded file externally and reloading it in Pyzo. Which messages does the Logger shell print?
Does the whole Pyzo IDE freeze when the problem occurs, or can you still use the mouse to do some actions in the Pyzo IDE when that problem occurred? Are there any widgets in the Pyzo IDE which still react to keyboard inputs (for example search fields)?
Do keyboard shortcuts still work after the problem occurred?
Does the problem also occur when all Pyzo tools (via the "Tools" menu) are closed before you reproduce the bug?
Does the problem also occur when you click "Keep this version" in the "File was changed" dialog?
Does the occurence of this problem depend on the code you executed before reloading the file?
Has the location of the file (that is modified and reloaded) an influence (e.g. external storage or local hard disk drive)?

You could also try to run Pyzo from source. Download the source code (e.g. [here](https://github.com/pyzo/pyzo/archive/refs/tags/v4.15.0.zip) or [here](https://github.com/pyzo/pyzo/archive/refs/heads/main.zip)), extract the contents to a folder and execute the script "pyzolauncher.py" -- this requires a Qt wrapper (e.g. PySide6, PyQt6, PySide2, PyQt5) to be installed in your Python interpreter.

**Comment by raymanP** [comment]
Hi @bdieterm , thank you for you reply and supportive inputs.
I tried out and it seems like that:

- When editing code in Pyzo, then changing in externally and afterward reload the file, the keyboard is blocked on all tools.  The Pyzo is not frrezed, just the keyboard is blocked. I can still use copy and paste with the mouse. Keyboard shortcuts are working also. Copy shortcut is blocked too, but if I copy externally then paste shortcut works in any tool and regains the keyboard funtionality In the logger tool nothing appears.
- If I the open the advanced settings or the key mappings window and close it, then keyboard functionality is regained too, until the steps above are repeated
- The problem also occurs with all tools closed
- Also the problem occurs when "keep this version" is chosen
- It is not needed to execute any code (maybe there are cases, but it seems it is related to the code editing like described above)

**Comment by almarklein** [comment]
Oh ... I have this too sometimes. I just `Command+Tab` to another window and then back, and it's fine again.

Funny, how one gets used to stupid workarounds like that, and I never bothered to try and fix it 🙃 

I will have a look
