### ISSUE TITLE
4.16 failed: "No module named 'PyQt5.sip'"

### ISSUE THREAD

**Issue by wolfgangr** [pyzo/pyzo#1053]
expected behaviour (as works in 4.15):
pyzo starts normally

```
wget https://github.com/pyzo/pyzo/archive/refs/heads/main.zip
... unzip ... mv ....
~/test/pyzo/pyzo_dev_4_15/pyzo-main$ ./pyzolauncher.py 
```

... and uses Qt 5, obviously:
```
Version info
Pyzo version: 4.15.0 (source)
Platform: linux
Python version: 3.7.3
Qt version: 5.11.3
PyQt5 version: 5.11.3
```

================

same procedure in 4.16 does not work:
```
~/test/pyzo/pyzo_dev_4_16/pyzo-main$ ./pyzolauncher.py 
Traceback (most recent call last):
  File "./pyzolauncher.py", line 54, in <module>
    pyzo.start()
  File "/home/wrosner/test/pyzo/pyzo_dev_4_16/pyzo-main/pyzo/__init__.py", line 54, in start
    from ._start import start
  File "/home/wrosner/test/pyzo/pyzo_dev_4_16/pyzo-main/pyzo/_start.py", line 16, in <module>
    from pyzo.util import paths
  File "/home/wrosner/test/pyzo/pyzo_dev_4_16/pyzo-main/pyzo/util/paths.py", line 7, in <module>
    from pyzo.qt import QtCore
  File "/home/wrosner/test/pyzo/pyzo_dev_4_16/pyzo-main/pyzo/qt/__init__.py", line 65, in <module>
    from . import qtutils
  File "/home/wrosner/test/pyzo/pyzo_dev_4_16/pyzo-main/pyzo/qt/qtutils.py", line 19, in <module>
    import PyQt5.sip as _sip
ModuleNotFoundError: No module named 'PyQt5.sip'
```

just an idea:
Just before upgrading, I have compiled and installed 3.12 on my system.
I see that pyzo found it and offered my to run shells with it.
Have even installed PyQt6 and run matplotlib from inside pyzo 4.15

May be that pyzo 4.16 uses new python and does not find qt?

**Comment by wolfgangr** [comment]
As a workaround, I tried `pyzo-4.16.0-linux_x86_64.tar.gz` from distro page instead of dev variant
get

```
wrosner@wjrws3:~/test/pyzo/pyzo_main_4_16$ ./pyzo 
[24233] Failed to load Python shared library '/home/wrosner/test/pyzo/pyzo_main_4_16/_internal/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/wrosner/test/pyzo/pyzo_main_4_16/_internal/libpython3.9.so.1.0)

wrosner@wjrws3:~/test/pyzo/pyzo_main_4_16$ python3 -V
Python 3.7.3

~/test/pyzo/pyzo_main_4_16$ la  /lib/x86_64-linux-gnu/libm.so.6 
lrwxrwxrwx 1 root root 12 Oct  8  2022 /lib/x86_64-linux-gnu/libm.so.6 -> libm-2.28.so
```

Time to update my debian??

**Comment by bdieterm** [comment]
The error "No module named 'PyQt5.sip'" means that either an older PyQt5 version <= 5.10.1 was used when executing pyzolauncher.py or that Python package "PyQt5-sip" is missing.
So in your case (you use PyQt5 v5.11.3) a missing "PyQt5-sip" package seems to be the problem. (When installing PyQt5 via pip, the "PyQt5-sip" package is installed automatically.)

You can add that package to the system's Python by running
`sudo apt install python3-pyqt5.sip` in a terminal (because you are using debian).
Then running Pyzo v4.16 should work on your system.

When running Pyzo, there are at least two (different) Python interpreters involved. The one that runs the Pyzo IDE (for example by executing pyzoloauncher.py) and the one that you see in the Python shell inside Pyzo. The error you reported was because of the Python (and PyQt5) that ran the Pyzo IDE.

Why did it work with Pyzo v4.15 and not Pyzo v4.16?
Pyzo v4.16 now uses function `sip.isdeleted` to check if a Qt object was deleted by the Qt libs.

> Time to update my debian??

According to your system's Python version (3.7.3) you seem to be running Debian 10.0 (Buster) which was released in July 2019. The debian security support for that version ended almost two years ago (see https://endoflife.date/debian).
And Python 3.7 does not receive security fixes anymore (see https://devguide.python.org/versions/).

So I highly recommend to update your debian.

**Comment by wolfgangr** [comment]
... never change a running system .... ;-\\\

Now I found that the SIP files obviously are located in  pyqt5-dev
```
~$ apt-cache show pyqt5-dev
Package: pyqt5-dev
Source: pyqt5
Version: 5.11.3+dfsg-1
Installed-Size: 3282
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: all
Depends: python3-sip-dev | python-sip-dev
Description-en: Development files for PyQt5
 This package contains the source SIP files from which the Python
 bindings for Qt5 are created. They are needed for building PyQt5
 as well as creating bindings for own Qt5 widgets written in C++.
```

Before I tried to install, I checked pyzo 4.16 ... and ... oh wonder:
It magically works without...
Python dependency is still a huge riddle for me....
