### ISSUE TITLE
Infinite TypeError on startup

### ISSUE THREAD

**Issue by louleke7** [pyzo/pyzo#1093]
Using Pyzo 4.12.3 on Debian 12

In the default config, starting a new shell gives me the following lines

```
Python 3.11.2 (main, Aug 26 2024, 07:20:54) on linux (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
Type 'help' for help, type '?' for a list of *magic* commands.
TypeError: notify(self, a0: QObject, a1: QEvent): first argument of unbound method must have type 'QApplication'
TypeError: notify(self, a0: QObject, a1: QEvent): first argument of unbound method must have type 'QApplication'
TypeError: notify(self, a0: QObject, a1: QEvent): first argument of unbound method must have type 'QApplication'
...
```
With these last lines repeating infinitely. 

After reading [#832](https://github.com/pyzo/pyzo/issues/832) , i tried changing the GUI from auto to PyQT5 or 6.

Selecting the GUI PyQt6 gives the following startup lines: 
```
Python 3.11.2 (main, Aug 26 2024, 07:20:54) on linux (64 bits).
This is the Pyzo interpreter. Failed to integrate event loop for PYQT6: setQuitOnLastWindowClosed(quit: bool): argument 1 has unexpected type 'PyQt6.sip.wrappertype'
```

PyQt5 seems to work perfectly, and so fixes the issue: 
```
Python 3.11.2 (main, Aug 26 2024, 07:20:54) on linux (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
```
and then all my scripts run fine, which is a bit weird to me since the "auto" selection seemed to pick PyQT5 too.

I haven't been able to replicate the problem by selecting any GUI manually, only with "auto" I have this infinite loop.

I open this issue for reference only, since it's already "solved" (change the GUI selection from auto to PyQT5) in my case.
Hope it helps anyone encountering the same issue, or any dev willing to tackle that!

For info : 
pip list | grep Qt : 
```
PyQt5               5.15.9
PyQt5-sip           12.11.1
PyQt6               6.4.2
PyQt6-sip           13.4.1
PyQt6-WebEngine     6.4.0
PyQtWebEngine       5.15.6
QtPy                2.3.0
```

**Comment by bdieterm** [comment]
Hi @louleke7,
thanks for the report.

I tried to reproduce your problems using a Docker container with a Debian 12 "bookworm" with packages installed so that `pip list | grep Qt` gives exactly the same output that you posted. And I installed the old Pyzo version via `apt install pyzo` to also get v4.12.3.

I was not able to reproduce your first problem with the "TypeError" output.

But I was able to reproduce the problem that occurs when selecting "PyQt6" as the "gui" for the event loop.
Pyzo v4.12.3 was released in March 2022. Now we already have Pyzo v4.17.0 with lots of bug fixes and new features, and the problem with PyQt6 is also solved.

You can run that new version in Debian 12 from source, as described in the Readme.md:
https://github.com/pyzo/pyzo#running-pyzo-from-source
