### ISSUE TITLE
Warning about shellhistory.py during startup

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#347]
Originally reported by: **Almar Klein (Bitbucket: [almarklein](http://bitbucket.org/almarklein), GitHub: [almarklein](http://github.com/almarklein))**

---

I get this on startup on some machines. Probably happens when the history tool has not been used yet. Seems to have no negative effects. But looks a bit sloppy.

```
An error occurred while loading the history: [Errno 2] No such file or directory: '/home/hector/.iep/shellhistory.py' 
```

cc @rreilink 

---
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/347

**Comment by rreilink** [comment]
The HistoryViewer tries to create that file when it does not exist. I suppose this happens when pyzo.appDataDir does not exist or is not writable. 

Adverse effect would be that history is not stored, so the error should not be muted IMHO

@almarklein I cannot reproduce it, can you check that /home/hector/.iep exists and is writable on the machines where this occurs?

**Comment by almarklein** [comment]
I suspect that the `.iep` dir was not created yet, so that writing the file fails. Looking at the `__init__.py` as it is now, the appdata seems to be created. Maybe it was not at the time of this issue (it's quite old)...

**Comment by almarklein** [comment]
Closing. The command history is now globally maintained by core Pyzo. So many code around this has been changed.
