### ISSUE TITLE
Brace matching take strings into account

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#366]
Originally reported by: **Almar Klein (Bitbucket: [almarklein](http://bitbucket.org/almarklein), GitHub: [almarklein](http://github.com/almarklein))**

----------------------------------------

We now have brace matching, but it fails when you have ``foo('some ) string')``

cc @EelkeSpaak 

----------------------------------------
- Bitbucket: https://bitbucket.org/iep-project/iep/issue/366

**Comment by ysalmon** [comment]
This could be solved by restricting brace-matching to portions of the code that lie out of string literals, and just skipping over string literals. Doing so can be done by reusing the logic of the code that colours the string literals.

**Comment by ysalmon** [comment]
Skipping string literals is not sufficient ; comments should also be skipped.

**Comment by ysalmon** [comment]
Here is a commit bb512b78ee85e69548cadaf43c91e0080280f819 adding support for parenthesis in the python parser. The next step would be to modify the HighlightMatchingBracket class to iterate over tokens instead of characters, but my understanding of how the different modules of pyzo interact is too poor for this.

**Comment by ysalmon** [comment]
The current implementation is really flawed, not only because of strings and comments : it will consider ([)] as matched. Counting opening and closing parenthesis of the same kind is not sufficient, one must use a stack.

**Comment by ysalmon** [comment]
I think I got it right in the updated #387 . Can you review it @almarklein ?

I modify the highlighter to store the current block's token list as a part of its userData.
This enables the brace-matcher to fetch these token lists in both directions (instead of reparsing, which would be extremely difficult when going backwards). One skips over undesired braces automatically because those are not included in the token lists.

Storing token lists in blocks may also enable some improvements in other extensions which can now dispense from reparsing parts of the document.
