### ISSUE TITLE
When frozen, do not use sys.path[0] to establish executable dir

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#442]
I installed pyzo 4.3.1 and it crashed at starting (using command line), with the following message:

Traceback (most recent call last):
  File "/home/almar/miniconda3/lib/python3.5/site-packages/cx_Freeze-5.0-py3.5-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "/home/almar/py/pyzo/pyzo/__main__.py", line 38, in <module>
  File "/home/almar/py/pyzo/pyzo/__main__.py", line 31, in application_dir
RuntimeError: Cannot determine app path because sys.path[0] is empty!

But there is no /home/almar directory.

**Comment by almarklein** [comment]
mmm, it seems that cx_freeze changed the value of sys.path[0]. It used to point to the executable. I thought that now it contained the dir of the executable. But that's not entirely through either, it seems. Probably it is if you double-click the executable, but if you run from the terminal from the same directory, then it's just the "current directory" (i.e. empty string).

Thanks for the heads-up!

**Comment by yltang52** [comment]
I installed pyzon at `/opt/pyzo`.
It runs OK from the its own directory (`cd /opt/pyzo; pyzo`).
However, it crashes if I run it at other directories (e.g., `cd; pyzo`). The error message listed above appear and pyzo won't start.

**Comment by yltang52** [comment]
Using the other [installation method](http://www.pyzo.org/install_linux.html#install-linux) solves the problem.

**Comment by almarklein** [comment]
Opened and renamed, because this is something that we can and should resolve.

**Comment by almarklein** [comment]
I am not sure why we did not use `sys.executable`, maybe because it can be relative ...  Should probably ask the cx_Freeze devs.

**Comment by almarklein** [comment]
Hey @takluyver, I used to use `sys.path[0]` in several projects to establish the directory that contains the executable. So far this has worked flawlessly, but with the current master of cx_Freeze it is broken. Any idea what's best used instead? IIRC `sys.executable` had problems on its own. Thanks!

**Comment by takluyver** [comment]
Hi Almar!

Looking at the Python docs on [PySys_SetArgvEx](https://docs.python.org/3.5/c-api/init.html#c.PySys_SetArgvEx), it looks it adds an empty string to `sys.path` if `argv[0]` "doesn’t point to an existing file name". I guess that's what's happening. I've usually recommended using `sys.executable` in frozen apps to find where it's located (e.g. [cx_Freeze FAQ](http://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files)), so if that doesn't work I'd consider it a bug.

I don't do much with cx_Freeze any more since I started working on [Pynsist](http://pynsist.readthedocs.io/en/latest/), though.
