### ISSUE TITLE
whitespace in blank lines

### ISSUE THREAD

**Issue by hudcap** [pyzo/pyzo#600]
I'm running Pyzo 4.7.3 on Windows 10.

Starting with one of the recent versions (can't say which for sure, but almost certainly >= 4.7), whenever I save a file, the whitespace is removed from lines that contain only whitespace.
The behavior is not completely consistent, but I haven't figured out the pattern yet.
My `removeTrailingWhitespaceWhenSaving` setting is set to 0, although if I'm not mistaken, whitespace on blank lines shouldn't be considered trailing even if I had turned this option on.

**Comment by hudcap** [comment]
I have a sneaking suspicion that is has something to do with cc5302718978fed7b076ef577f4ab23a8da98110, although I could be way off.

**Comment by almarklein** [comment]
Since 4.7.0 Pyzo will remove trailing whitespace if the original file contained very little whitespace. The "very little" means "less than 10 lines" from the top of my head. This is probably what makes it feel inconsistent. The idea is to leave files mostly intact to avoid massive Git diffs for small changes, but apply ws removal when it makes sense.
