### ISSUE TITLE
When completing an autocompletion, the interactive help resets

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#649]
I found my students struggling with this a bit:
* Type `<something>.`
* Scroll through autocompletion list
* Hit tab to complete
* Start reading interactive help ... except that it has reset :)

@ysalmon thoughts?

**Comment by ysalmon** [comment]
Yes, I understand it may be annoying.

IIRC, when autocomplete ends, the help tool cannot know whether it is because autocompletion failed/was refused (in which case we should discard the related help) or it was on the contrary accepted.

I think things could be differentiated [there](https://github.com/pyzo/pyzo/blob/ebc985b807e3a5ef81f2983cad10ef37d023e9d1/pyzo/codeeditor/extensions/autocompletion.py#L145) : that ``onAutoComplete`` calls ``autocompleteCancel`` and not ``autocompleteAccepts`` (which does nothing) is rather odd.
