### ISSUE TITLE
Auto completion fails inside class

### ISSUE THREAD

**Issue by wojnilowicz** [pyzo/pyzo#659]
Auto completion works for a class variable when used outside of the class while it fails when used inside the class.

Steps to reproduce:
1) run script attached below (it should finish successfully in order to get any completion at all)
2) uncomment 9th line and try auto complete "class_instance.my_database_connection" variable (it should work)
3) uncomment 6th line and try auto complete "self.my_database_connection" variable

Result:
Auto completion doesn't work.

Expected result:
Auto completion should work.

Version:
Pyzo 4.9 from Fedora 31

Script:
```
import mysql.connector

class SimpleClass:
    def __init__(self):
        self.my_database_connection = mysql.connector.connect()
        #self.my_database_connection.

class_instance = SimpleClass()
#class_instance.my_database_connection.
```

**Comment by almarklein** [comment]
This behavior is expected (though I can imagine a user might expect otherwise).

In the case with `class_instance.my_database_connection.` Pyzo has a reference to the database connection object that it can inspect and produce an autocompletion list. In the case with `self.my_database_connection.` Pyzo knows that `self` is a `SimpleClass`, but it does not know what `self.my_database_connection` is, because that requires an instance of the class.

In this case, an instance does exist, but detecting this and use it to make assumptions about how all instances work is not trivial, and not implemented in Pyzo.

**Comment by wojnilowicz** [comment]
What if my_database_connection's type would be hinted like this (see 4th line)
```
import mysql.connector

class SimpleClass:
    my_database_connection: mysql.connector.MySQLConnection
    def __init__(self):
        self.my_database_connection = mysql.connector.connect()
        # self.my_database_connection

class_instance = SimpleClass()
# class_instance.my_database_connection
```
Would autocompletion be easy to implement in hinted type case?

I would like to note that PyCharm works here as I expect it. Can you suggest any workaround for working with Pyzo and getting autocompletion in context of a class?

**Comment by almarklein** [comment]
That would be an excellent way to make Pyzo's autocompletion work again. However, Pyzo's parser is not yet aware of type annotations. I would love to add it, like so many other improvements, but I lack the time :(

What I do sometimes, is run the code, so an instance exists, then in the shell run `self = class_instance` and that fools Pyzo into using the instance object where you type `self`.
