### ISSUE TITLE
Encoding in shell

### ISSUE THREAD

**Issue by hg2051** [pyzo/pyzo#668]
I'm working with text files in finnish, utf8 encoded.
Upon opening, reading and displaying its content, utf seems inactive.
Writing back the files gives normal text (the original)
Working with IDLE doesn't have the same problem.
Any solution?

```py
# -*- coding: utf-8 -*-
# Python program to generate word vectors using Word2Vec

# importing all necessary modules
import codecs
import nltk
# nltk.download('punkt')
from nltk import punkt
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings

warnings.filterwarnings(action = 'ignore')

import gensim
from gensim.models import Word2Vec

#  Reads ‘TUUKAN POIKA.txt’ file
sample = codecs.open(r"E:\Finnish books\TUUKAN POIKA.txt", "r",'UTF-8')
s = sample.read()
print(s)

Sample:  ä appears as Σ
```
*edited by AK to format the code as monospace Python*

**Comment by almarklein** [comment]
Probably unrelated, but why are you using `codecs.open()` instead of just builtin `open()`?

Assuming that `codecs.open()` works the same way as `open()`, sample should be a (Unicode) str object with the correct characters. Not sure why the char is printed wrong.

Could you try `ord(c)` to get the Unicode id for that character? That should help determine if its really correct.

**Comment by hg2051** [comment]
I found the solution. I had chosen "Terminal" as font, without knowing it
doesn'work with utf-8. I'm sure it should no longer figure as a choice, as
Python encodes in utf-8.

**Comment by almarklein** [comment]
It's not that that font (or any font) does not work with UTF-8. The problem is that the font does not support that specific character.

UTF-8 is an encoding, which means that it is a method for converting Unicode strings to bytes. UTF-8 is very nice because it can encode *any* Unicode character and still be compact for characters in the ASCII range. Characters in a Unicode string are identified with an integer number (the Unicode code point, what `ord()` returns).

Fonts render the visual representation of these Unicode code points. I don't think there are fonts that can render all existing Unicode code points, but some fonts can render a lot, i.e. they have support for characters from many different languages. Some fonts, usually older fonts, are limited in the code points that they support. My guess is that the "Terminal" font can render only code points from the ASCII range.

**Comment by hg2051** [comment]
SURELY Terminal is not suited for umlaut characters.
That's why it should disappear from the font choices in Python IDEs like
Pyzo.

**Comment by almarklein** [comment]
> That's why it should disappear from the font choices in Python IDEs

I agree in principal. But Pyzo lists all monospace fonts found on the system, and as far as I know, it's not possible to detect the reach of Unicode characters of a font beforehand.

That said, I'd love to be proven wrong on that :) If it's possible, I'd love to mark/remove these fonts.
