### ISSUE TITLE
Disable FONTCONFIG_FILE env variable for kernels

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#685]
We set `os.environ['FONTCONFIG_FILE']` [here](https://github.com/pyzo/pyzo/blob/master/pyzo/__init__.py#L63). Supposedly it was [added](https://github.com/pyzo/pyzo/commit/e1266e0e9f5f91fa0a0c2331f2da9399933b57aa#diff-94822694969a9a97f828619d86d1e5ad) to "make frozen Pyzo work for Linux again" in sept 2016. That was before we used PyInstaller.

We should check whether this is still needed at all. If not, let's just remove it. Otherwise, we should strip that variable from the env that is provided to the kernels (in `kernelbroker.py`).

cc @Tontyna

**Comment by almarklein** [comment]
While we're in there, maybe also pop `LD_LIBRARY_PATH` if it's an empty string (after we remove the root frozen directory).

**Comment by Tontyna** [comment]
> We should check whether this is still needed at all.

Since we run on Linux the system probably possesses a fully functional `fonts.conf`. This config file fulfills the requirements of the system's FontConfig library. Not necessarily the needs of the frozen FontConfig -- the warning concerning `FcBlanks` is just an example what might be different.

I'm not happy with the `linux_fonts.conf` from Pyzo's resources folder, it should be the `fonts.conf` from the build system... or at least a config file that satisfies the build system's FontConfig version.

BTW: There is an easier way to restore the original `LD_LIBRARY_PATH` -- see [LD_LIBRARY_PATH / LIBPATH considerations](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations) in the PyInstaller docs.

Looks like PyInstaller only preserves an `*_ORIG` value for the `LD_LIBRARY_PATH` and not for all modified environment variables.

**Comment by almarklein** [comment]
I don't know too much about font config files. Do you have time to look into this, and maybe submit a PR?

> BTW: There is an easier way to restore the original LD_LIBRARY_PAT

Oh, nice!

**Comment by Tontyna** [comment]
Diving a bit into PyInstaller, FontConfig and Linux dependency hell made me sad and angry and disappointed: We are doomed to fail. 

This said, I checked why Pyzo's own `linux_fonts.conf` was introduced and stumbled upon #408.
Looks like pointing `os.environ['FONTCONFIG_FILE']` to this file was a workaround to get rid of a MiniConda feature: local paths in the frozen application; cf. https://github.com/pyinstaller/pyinstaller/issues/3438

Since we don't freeze on MiniConda anymore the workaround is obsolete, the frozen libfontconfig should load the system's default config file automatically.

@almarklein -- shall I create a PR that just comments out the `os.environ["FONTCONFIG_FILE"]` and then wait and see? 

Of course: 

* There is no guarantee that there is a default font config file on the system. It's unlikely, but nevertheless...

* There is no guarantee that the system's font configuration matches the frozen libfontconfig's requirements -- catchword: FcBlanks

An alternative approach might be to incorporate the *build system's* default config file `/etc/fonts/font.conf` into our Pyzo binary distribution. With PyInstaller's `--add-data` option we could get rid of the hand-made `linux_fonts.conf`.

Of course:

* There is no guarantee, either, that the build system's config file will integrate well into the system -- catchwords: search paths, cachedir, FcBlanks

In any case: FontConfig seems to be one of the minor library incompatibility issues lurking in the Linux binary.

**Comment by almarklein** [comment]
Thanks for digging into this! Yeah, let's just try to stop shipping our own version, and see what happens.
