### ISSUE TITLE
fozen Linux Pyzo: "File|Open" crashes

### ISSUE THREAD

**Issue by Tontyna** [pyzo/pyzo#686]
Binary Pyzo v4.10.2 on Linux crashes when I try to open a file. Console says:

```
symbol lookup error: /usr/lib/x86_64-linux-gnu/libgtk-3.so.0: undefined symbol: g_log_structured_standard
```

Seems to be another case of library mismatch :anger: :sob:

**Comment by almarklein** [comment]
:(

**Comment by almarklein** [comment]
reproduced

**Comment by almarklein** [comment]
Tweaked the build. I managed to actually build with 16.04, because Pyzo supports Python 3.5 again (somehow a dependency on 3.6 snuck in). Unfortunately, that version of Qt that comes with that has no hidpi support, so I changed to using 18.04. Binary here: https://github.com/pyzo/pyzo/releases/download/v4.10.2/pyzo-4.10.2.2-linux64.tar.gz

**Comment by almarklein** [comment]
We could actually build both, but we'd have to make sure to name the binaries differently.

**Comment by almarklein** [comment]
Pyzo website is updated to point at the new build.
