### ISSUE TITLE
The kernel process exited. (3221225477)

### ISSUE THREAD

**Issue by dream-rush** [pyzo/pyzo#708]
import TradeX2
clientHq = TradeX2.TdxHq_Connect('119.147.212.81', 7709)

This code can run in spyder IDE,but can't run in pyzo.

**Comment by almarklein** [comment]
Sorry, but I cannot help you if you do not provide more info. Please also explain what you expect, and what happens instead, including any warnings and error messages.

**Comment by Tontyna** [comment]
I don't know what `TradeX2.TdxHq_Connect` actually does, but I do know that my pyzo *kernel process exits* when I run code that calls `sys.exit(0)`

**Comment by almarklein** [comment]
> I don't know what `TradeX2.TdxHq_Connect` actually does

Me neither. The `TradeX2` that gets imported must be installed for it to work. This issue list is for issues with the Pyzo IDE, not with code that you run in it. I'm assuming that you're a Python beginner. This is fine, and I'd be happy to help. But if you don't provide any more information then you're wasting my time. I'd recommend getting a bit more familiar with Python, so that you have a better understanding of what you're doing and what goes wrong :)

> but I do know that my pyzo kernel process exits when I run code that calls `sys.exit(0)`

Great, because that's what it's supposed to do :)  (`sys.exit()` terminates the process, the optional parameter is the exit code.)

**Comment by dream-rush** [comment]
![2020-08-03_205707](https://user-images.githubusercontent.com/24774119/89185079-3ce66c00-d5cc-11ea-815b-0056d67c322b.png)
![2020-08-03_210052](https://user-images.githubusercontent.com/24774119/89185216-74551880-d5cc-11ea-86b1-771b0fb65e0d.png)

import TradeX2
clientHq = TradeX2.TdxHq_Connect('222.90.136.119', 7709)

I try this code in pyzo 4.9 and 4.10, it can't run.

but when I write like this:

import TradeX2
lst=[]
lst.append(TradeX2.TdxHq_Connect('222.90.136.119', 7709))
lst[0]
errinfo, count = lst[0].GetSecurityCount(0)

it can run.
I think it's a bug.

**Comment by almarklein** [comment]
Thanks for the additional info. This helps. And I agree that this bahaviour is surprising. What exactly is `TradeX2`? Is there a way for me to try and reproduce this?
