### ISSUE TITLE
Run the program MacOS

### ISSUE THREAD

**Issue by Help754** [pyzo/pyzo#730]
Hello.
I code a window and when I started the program the window do not appears... But I tried on a windows laptop and my code worked. I don't know how to do, can you help me fix that issue because I need to code quickly for a work. 

Thanks

**Comment by almarklein** [comment]
Hi!

I'm not sure if I follow your question. I think you've coded a GUI application. Are you using PyQt? You're saying the window does not appear. Are there any warnings or errors?

**Comment by Help754** [comment]
Hi !

There is no warnings or errors. And when I run the script under windows it worked. The problem came from Mac I think but I don't know how to fixe it...
I'm using tkinter to code a game.
Pyzo worked until I want to use a graphical interface like Tkinter

**Comment by almarklein** [comment]
TkInter on MacOS has always been a bit buggy. See e.g. [this](https://www.python.org/download/mac/tcltk/). You can try following the instructions in that link. Maybe it helps to put Pyzo's shell integration to tkinter (menu > shell > edit shell configurations).

Otherwise, I'd recommend using PyQt5 for building GUI's, as it's much more stable across platforms.
