### ISSUE TITLE
Graphviz and Pyzo

### ISSUE THREAD

**Issue by jowe19** [pyzo/pyzo#757]
Hi, I try to execute the following code. 

```
from graphviz import Digraph
import pydotplus

dot = Digraph(comment='The Round Table')

dot.node('A', 'King Arthur')
dot.node('B', 'Sir Bedevere the Wise')
dot.node('L', 'Sir Lancelot the Brave')
dot.edges(['AB', 'AL'])
dot.edge('B', 'L', constraint='false')

print(dot.source)
dot.render('test-output/round-table.gv', view=True)
```

Everything works fine when I run it from a shell (`graphviz` is installed with homebrew on MacOS), but with Pyzo I get the following error : 

<img width="643" alt="Capture d’écran 2021-09-06 à 10 57 43" src="https://user-images.githubusercontent.com/19306526/132189796-bc786a4d-9b47-4d75-bf47-efe11c12a207.png">

**Comment by almarklein** [comment]
I hate to use this line, but have you restarted Pyzo since installing graphviz and/or pydotplus? It looks like the installation adds something to the PATH env variable, and Pyzo might simply not be aware yet.

Otherwise you could set `PATH` in your shell configuration's environment variables (menu > shell > edit shell config, and then the "environ" field).

**Comment by jowe19** [comment]
> I hate to use this line, but have you restarted Pyzo since installing graphviz and/or pydotplus? It looks like the installation adds something to the PATH env variable, and Pyzo might simply not be aware yet.
> 
I have restarted Pyzo, and the same message occurs. 

> Otherwise you could set `PATH` in your shell configuration's environment variables (menu > shell > edit shell config, and then the "environ" field).

So I have to add something in the `pythonPath` window ? 

<img width="626" alt="Capture d’écran 2021-09-10 à 15 12 24" src="https://user-images.githubusercontent.com/19306526/132858508-987e4251-5b24-4946-946f-d6990229868f.png">

**Comment by adddvent** [comment]
Hi jowe!

First step: find out in which directory the "dot" command binary is located
Open a shell and type the following command:
`which dot`
This will show something like
`/the_path/to_the_dot/command_directory/dot`

Second step: make sure that pyzo will have this path in the environment variables
One way to do this is to add the path to the "environ" field in the pyzo shell config, as @almarklein suggested, and it works like this:
Your screenshot of the shell configuration does not show the "environ" textbox below the argv textbox because the vertical scrollbar is hidden in MacOS by default. So scroll down a bit and add a new line at the end of the environ textbox (use the proper path of the directory where the dot command is located):
`PATH="$PATH:/the_path/to_the_dot/command_directory"`
Then press the "Done" button and restart the python shell within pyzo (or just restart the whole pyzo application).

Why is it necessary to add this path in pyzo when it works just fine when running the python script directly from a shell? I have no MacOS experience, but it seems to be very similar to Linux, having the same issues. I guess that during the graphviz installation, the PATH variable was just added to a file like ".bash_profile". When starting pyzo directly, this file will be ignored, but when you start a shell and type the path of the pyzo binary inside the shell to execute it, pyzo will inerhit the shell environment variables and thus the dot command will be found without modification of the pyzo shell config. If my assumption is correct, the other solution would be to add the path to the dot command in a different configuration file, as described in https://serverfault.com/questions/132016/how-to-set-path-variable-on-mac-os-so-that-even-non-terminal-apps-see-it

I hope this helps.

**Comment by jowe19** [comment]
Thanks @adddvent for your answer. The command `which dot` give `/usr/local/bin/dot`. So the "environ" textbox is now 
<img width="571" alt="Capture d’écran 2021-09-12 à 17 59 49" src="https://user-images.githubusercontent.com/19306526/132994603-a75b33c3-059c-4527-af04-4d5f5282963a.png">

Unfortunately I always get the same error message.

**Comment by adddvent** [comment]
Oops, my bad! Please remove the quotes in the environ field, so:
`PATH=$PATH:/usr/local/bin`

**Comment by jowe19** [comment]
Works perfectly, thanks ! 😊

**Comment by almarklein** [comment]
> Works perfectly, thanks ! 

Great!

Thanks for chiming in @adddvent !
