### ISSUE TITLE
GIL issue with scripts executed from pyzo shell config

### ISSUE THREAD

**Issue by LukeMacAleese** [pyzo/pyzo#808]
Whenever I execute some startup script in the shell config (either as a file or as command lines to execute at shell startup),
activating the matplotlib interactive mode (matplotlib.pyplot.ion()) results in the shell crashing at each attempt to plot a figure. The following message documents the crash: 
"Fatal Python error: PyEval_RestoreThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)"
followed by multiple lines of thread informations ("Thread 0x0000329c (most recent call first): ...")

Remarks: 
(1)this does not occur when the same startup code is run from the shell after startup.
(2)I cannot reproduce the error either when executing the exact same code from the python environment in the anaconda prompt.
(3)when no script is executed in shell config and matplotlib interactive mode is off, the command plt.show() shows the figure and gives back control (with a prompt) to the shell.
(4)on the contrary, whenever some startup script is executed in shell config and matplotlib interactive mode is off, the command plt.show() shows the figure but does not give back control to the shell and the prompt is back only after the figure is closed.

IMHO it may point at the possibility that the script executed in shell config does not use the same executables ... how could I check that ? any other idea of the origin of this dysfunction ?

thanks! Luke

System info:
OS Win10 64 bits
environments managed with anaconda (base = python 3.9)
Python 3.9.12 (main, Apr  4 2022, 05:22:27) on Windows (64 bits). (nut same in environments with python versions 3.8 and 3.10)
Pyzo version: 4.12.3 (binary)
Platform: win32
Python version: 3.10.2
Qt version: 6.2.3
PySide6 version: 6.2.3

**Comment by almarklein** [comment]
Hi, thanks for the detailed report!

I don't know why this is happening, but my guess would be that at the time that the startup script is run, Python is not ready yet to go into interactive mode. Have you tried putting the code after the line "# AFTER_GUI "? 

> IMHO it may point at the possibility that the script executed in shell config does not use the same executables

No, this should be fine. Each shell is attached to a single Python process. The startup code is run as part of the process of starting up the interpreter, just like setting up GUI integration. After that, any incoming commands are executed in the very same process.

As a tip, you could try making (more) use of the feature to mark a file as the MAIN file so that it can be executed more easily. Or you could create a small module that you import where needed.

**Comment by LukeMacAleese** [comment]
Dear Almar, thanks for your answer and suggestions
the #after_gui test did not change anything,
however I've just updated all my environments (python 3.9 and 3.10) in anaconda (including matplotlib and pyqt) and the error disappeared... not sure what it was but happy it's behind me!
cheers, Luke
