### ISSUE TITLE
Using the file browser causes a crash on MacOS with PySide 6.5.1 and up

### ISSUE THREAD

**Issue by almarklein** [pyzo/pyzo#887]
* On MacOS, as you browse, the first item from the parent directory is shown. 
* Also, when changing the filter field, Pyzo crashes.
* Also observed a crash when just browsing the files once.
* This bug does not appear to occur on the last binary release (4.12.8, which uses PySide 6.4.3).
* I [tried undoing](https://github.com/pyzo/pyzo/pull/888) #871, because that is the only change that looked somewhat suspicious to me, but that does not seem to be the cause.
* This bug does not appear on the latest source version, when using Pyqt6.
* But when I run Pyzo locally on the latest version of PySide6 (6.5.1.1), it already crashes when I click a folder in the file browser.

So it looks like this bug is specific to PySide6.

**Comment by almarklein** [comment]
@bdieterm you've done a lot of work on Qt lately, any ideas?

**Comment by bdieterm** [comment]
@almarklein 
I just tested this again in Linux with PySide6 6.5.1.1 (running it from source) and in Windows 10 (with PySide6 6.5.1.1 as shipped in the new release) -- both work normally.

As you mentioned, the problem seems to occur only with MacOS and PySide6 6.5.1.1.

If I had access to a MacOS computer, I would try the following steps to find out more about the cause:
* disable file icons by inserting `return` directly after line `def setFileIcon(self):` for each `class DirItem(BrowserItem)` and `class FileItem(BrowserItem)`
* when running pyzo from source, start it by executing "pylauncher.py" because this is the only way that contains `faulthandler.enable()` -- maybe this gives some valueable extra information
* set breakpoints in places like `class Tree` function `onChanged`, then launch pyzo inside pyzo and step through (or add newer breakpoints on the fly and run till the next breakpoint) to see where the crash happens
* install older versions of package PySide6 (e.g. the one that was also used in Pyzo 4.12.8) and find the newest version without crash and the oldest version where the crash still happens

Let me know about your findings -- I will gladly help you to solve this.

**Comment by almarklein** [comment]
The problem occurs in PySide 6.5.1 and 6.5.1.1. It works fine in 6.5.0, and the release before it 6.4.3 (which is what the previous Pyzo release was built against). See [list](https://pypi.org/project/PySide6/#history).

**Comment by almarklein** [comment]
The error originates here:
https://github.com/pyzo/pyzo/blob/571a55a653ea5cc66419c34345d4e1bd2c053101/pyzo/tools/pyzoFileBrowser/tree.py#L674

If I just comment that line, it crashes on a later call to `setCurrentItem()`.

I'm not sure if we're using the tree in a bad way that now breaks, or whether this is simply a bug in PySide6. I briefly searched in [their issue tracker](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2371?filter=allopenissues).

I think I'll pin Pysyde6 to `<=6.5.0`. I'm curious to the next version of PySide ...

**Comment by almarklein** [comment]
I released a new version that builds the macos binary on 6.4.3.

**Comment by almarklein** [comment]
This appears fixed now. Confirmed in 6.5.0 and 6.6.0.

**Comment by almarklein** [comment]
If I comment the lines that make it error on 6.5.3, it works again. If I try with that code on 6.5.1, it still crashes. So I think it's unrelated. Still suspicious.

For now I put the code that errors on 6.5.3 in a try-except block, making it work for that version again. See #927.
