### ISSUE TITLE
pyzo debugger with multiple files

### ISSUE THREAD

**Issue by risky777** [pyzo/pyzo#978]
On pyzo 4.15.0, I have question about debugging project with several py-files.

I open interesting files in my project:
- "start.py" = starter script without other code
- "main.py" = script containing code I want to debug
Then I open "Tools / Editor list" and there in context menu mark "start.py" with "Set/Unset as MAIN file".

When I want to debug I run "Run / Run main file as script". My project runs, but pyzo ignores breakpoints set in "main.py". I've placed "print..." commands next to breakpoints and they show that this code is executed, but breakpoints don't work?

**Comment by bdieterm** [comment]
I tried to reproduce your problem but, given the scarce description, I was not able to.


This is an example that works perferctly on my Linux system:

contents of file /tmp/start.py, set as MAIN file, and opened in the editor:
```python3
import os
os.chdir('/tmp')
import test_main
```
contents of file /tmp/test_main.py, and also opened in the editor:
```python3
print('aa')
bb = 2  # <-- normal breakpoint in this line (full red circle)
print('bb')
```
"Run -> Run main file as script" will stop the interpreter at the breakpoint and you can debug there with Pyzo.
For this example you have to restart the shell (or to reload the module) before you run this a second time. Otherwise the Python interpreter will not execute that code in the imported module again -- you can see that the print functions will not be executed again.

Can you please:
1. try this code
2. provide a minimum or reduced example to reproduce the problem (the two Python scripts) 

By the way: You can also set a file as the MAIN file via the context menu that opens when right clicking on the editor tab.

**Comment by risky777** [comment]
I've done some tests, on termux-aarch64. I got debugging-multiple-files working only in one procedure:
- Open start.py in pyzo. No need to mark it as main-file.
- Set breakpoint on place where another py-file (in my case main.py) is called.
- "Run / Run file as script"
- Execution stops at breakpoint.
- "Shell / Debug step into: proceed one step"
- main.py is opened by pyzo-debugger and execution stops at entry-point into main.py file.
- From now debugger will work correctly in main.py. Shell open/close doesn't matter, pyzo exit/open doesn't matter, this main.py must remain open between sessions.

Manually opened main.py is ignored by pyzo-debugger, only main.py opened by pyzo-debugger is relevant to pyzo-debugger.

I'm doing some modifications-testing on this project "https://github.com/DYefremov/DemonEditor/", so here's source if you need it.

**Comment by almarklein** [comment]
Could it be that you have two `main.py` files? E.g. one in your repo source, and one installed into site-packages? The debugger only triggers on files that it actually executes.

**Comment by bdieterm** [comment]
I tried again to reproduce the problem using the "DemonEditor" source code, but with no avail.
Setting only breakpoints in start.py and stepping into main.py works as well as only setting a breakpoint in main.py and stopping there when executing start.py. There was no issue with different versions of main.py files -- the debugger always switched to the main.py that was already open in the editor.

To expand on what @almarklein suggested:
@risky777, can you please:
- report the filepaths of the two main.py files: the one that you opened manually and the one that was opened by the debugger. You can copy the filepath by right-clicking on the editor's tab-head and selecting "Copy path".
- run a debug session so that you are stopped inside main.py (e.g. by setting a breakpoint inside main.py and running start.py) and then execute the magic command "db where" in the shell. This will print the stack trace with the filepaths. Can you also report that output?
- open the "Logger" tool in Pyzo (via the menu "Tools" -> "Logger"), run the debug session that will open the other main.py additionally to the manually opened one, and then copy all the output from the Logger tool. When Pyzo opens a file or tries to open a file, this can be seen there.

**Comment by risky777** [comment]
Problem solved. Path was problem. Termux doesn't run from its own root folder but uses android root folder. Because of this some important folders have up to 3 (mount) paths to same folder. I opened same file, but different path.

**Comment by almarklein** [comment]
Ah, thanks for the explanation!
